security:
    password_hashers:
        Pidia\Apps\Demo\Entity\Usuario:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: Pidia\Apps\Demo\Entity\Usuario
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: Pidia\Apps\Demo\Security\LoginFormAuthenticator
            logout:
                target: homepage
                enable_csrf: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
#            entry_point: 'custom_authenticator'
    access_control:
        - { path: '^/(%app_locales%)/login', roles: PUBLIC_ACCESS, methods: [ GET ] }
        - { path: '^/', roles: IS_AUTHENTICATED_REMEMBERED }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

        firewalls:
            main:
                http_basic: ~