parameters:
    locale: es
    app_locales: es|en
    default_results_per_page: { '5': 5, '10': 10,'25': 25, '100': 100, '1000': 1000 }
    app.attach_file_table_prefix: core_

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Pidia\Apps\Demo\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    CarlosChininin\App\Domain\Model\AuthMenu\MenuServiceInterface: '@Pidia\Apps\Demo\Service\Menu\MenuService'
